"""Add Phase 5 fields

Revision ID: 2f6fb99de915
Revises: 64847fbc785f
Create Date: 2026-09-23 18:17:33.678606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6fb99de915'
down_revision: Union[str, Sequence[str], None] = '64847fbc785f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibility_requirements', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('eligibility_requirements', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('eligibility_requirements', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('eligibility_requirements', sa.Column('extraction_method', sa.String(), nullable=True))
    op.drop_column('eligibility_requirements', 'page_number')
    op.add_column('important_dates', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('important_dates', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('important_dates', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('important_dates', sa.Column('extraction_method', sa.String(), nullable=True))
    op.drop_column('important_dates', 'page_number')
    op.add_column('medical_standards', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('medical_standards', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('medical_standards', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('medical_standards', sa.Column('extraction_method', sa.String(), nullable=True))
    op.drop_column('medical_standards', 'page_number')
    op.add_column('physical_standards', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('physical_standards', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('physical_standards', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('physical_standards', sa.Column('extraction_method', sa.String(), nullable=True))
    op.drop_column('physical_standards', 'page_number')
    op.add_column('raw_documents', sa.Column('extraction_method', sa.String(), nullable=True))
    op.add_column('raw_documents', sa.Column('parser_version', sa.String(), nullable=True))
    op.add_column('raw_documents', sa.Column('language', sa.String(), nullable=True))
    op.add_column('selection_stages', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('selection_stages', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('selection_stages', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('selection_stages', sa.Column('extraction_method', sa.String(), nullable=True))
    op.drop_column('selection_stages', 'page_number')
    op.add_column('vacancies', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('extraction_method', sa.String(), nullable=True))
    op.drop_column('vacancies', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('page_number', sa.INTEGER(), nullable=True))
    op.drop_column('vacancies', 'extraction_method')
    op.drop_column('vacancies', 'content_hash')
    op.drop_column('vacancies', 'page_end')
    op.drop_column('vacancies', 'page_start')
    op.add_column('selection_stages', sa.Column('page_number', sa.INTEGER(), nullable=True))
    op.drop_column('selection_stages', 'extraction_method')
    op.drop_column('selection_stages', 'content_hash')
    op.drop_column('selection_stages', 'page_end')
    op.drop_column('selection_stages', 'page_start')
    op.drop_column('raw_documents', 'language')
    op.drop_column('raw_documents', 'parser_version')
    op.drop_column('raw_documents', 'extraction_method')
    op.add_column('physical_standards', sa.Column('page_number', sa.INTEGER(), nullable=True))
    op.drop_column('physical_standards', 'extraction_method')
    op.drop_column('physical_standards', 'content_hash')
    op.drop_column('physical_standards', 'page_end')
    op.drop_column('physical_standards', 'page_start')
    op.add_column('medical_standards', sa.Column('page_number', sa.INTEGER(), nullable=True))
    op.drop_column('medical_standards', 'extraction_method')
    op.drop_column('medical_standards', 'content_hash')
    op.drop_column('medical_standards', 'page_end')
    op.drop_column('medical_standards', 'page_start')
    op.add_column('important_dates', sa.Column('page_number', sa.INTEGER(), nullable=True))
    op.drop_column('important_dates', 'extraction_method')
    op.drop_column('important_dates', 'content_hash')
    op.drop_column('important_dates', 'page_end')
    op.drop_column('important_dates', 'page_start')
    op.add_column('eligibility_requirements', sa.Column('page_number', sa.INTEGER(), nullable=True))
    op.drop_column('eligibility_requirements', 'extraction_method')
    op.drop_column('eligibility_requirements', 'content_hash')
    op.drop_column('eligibility_requirements', 'page_end')
    op.drop_column('eligibility_requirements', 'page_start')
    # ### end Alembic commands ###
