"""Add recruitment models

Revision ID: 64847fbc785f
Revises: 8dcecae8716b
Create Date: 2026-09-23 17:53:05.980392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64847fbc785f'
down_revision: Union[str, Sequence[str], None] = '8dcecae8716b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forces_name'), 'forces', ['name'], unique=True)
    op.create_table('source_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('force', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('official_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_registry_force'), 'source_registry', ['force'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('force_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('storage_location', sa.String(), nullable=False),
    sa.Column('extraction_status', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_raw_documents_content_hash'), 'raw_documents', ['content_hash'], unique=True)
    op.create_table('recruitment_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruitment_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['recruitment_categories.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['recruitment_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('important_dates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('date_value', sa.DateTime(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['recruitment_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_standards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['recruitment_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_standards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['recruitment_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['recruitment_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.document_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['recruitment_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_table('selection_stages')
    op.drop_table('physical_standards')
    op.drop_table('medical_standards')
    op.drop_table('important_dates')
    op.drop_table('eligibility_requirements')
    op.drop_table('recruitment_notifications')
    op.drop_table('recruitment_categories')
    op.drop_index(op.f('ix_raw_documents_content_hash'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_table('exams')
    op.drop_index(op.f('ix_source_registry_force'), table_name='source_registry')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_forces_name'), table_name='forces')
    op.drop_table('forces')
    # ### end Alembic commands ###
