"""Add fitness assessments

Revision ID: 8a31b80f4691
Revises: 2f6fb99de915
Create Date: 2026-09-24 01:41:22.656871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a31b80f4691'
down_revision: Union[str, Sequence[str], None] = '2f6fb99de915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('valid_reps', sa.Integer(), nullable=False),
    sa.Column('invalid_reps', sa.Integer(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('form_score', sa.Float(), nullable=False),
    sa.Column('form_warnings', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitness_assessments_id'), 'fitness_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_fitness_assessments_user_id'), 'fitness_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fitness_assessments_user_id'), table_name='fitness_assessments')
    op.drop_index(op.f('ix_fitness_assessments_id'), table_name='fitness_assessments')
    op.drop_table('fitness_assessments')
    # ### end Alembic commands ###
